apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: sushilsaroya/frontend:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: REACT_APP_PRODUCT_URL
          value: "http://product-service:5000"

        - name: REACT_APP_ORDER_URL
          value: "http://order-service:5001"

        - name: REACT_APP_INVENTORY_URL
          value: "http://inventory-service:5002"
